#!/bin/bash
FILE=kernel
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 --leak-check=full --show-leak-kinds=all ./$FILE
fi